### ISSUE TITLE
pip install fails on v 0.2.0

### ISSUE THREAD

**Issue by jburos** [hammerlab/cohorts#144]
I am seeing the following error when installing `cohorts` in a clean conda environment, using python 3.5:

```
(test-py35) admins-MacBook-Pro-2:cohorts jacquelineburos$ pip install cohorts --no-cache-dir
Collecting cohorts
  Downloading cohorts-0.2.0.tar.gz (53kB)
    100% |████████████████████████████████| 61kB 2.7MB/s
    Complete output from command python setup.py egg_info:
    [Errno 2] No such file or directory: '/private/var/folders/1x/v6qn3g750k1bh84j7m_36gpw0000gp/T/pip-build-r3nhhicf/cohorts/README.md'
    Failed to open /private/var/folders/1x/v6qn3g750k1bh84j7m_36gpw0000gp/T/pip-build-r3nhhicf/cohorts/README.md
    No module named 'pypandoc'
    Failed to convert %s to reStructuredText README.md
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/1x/v6qn3g750k1bh84j7m_36gpw0000gp/T/pip-build-r3nhhicf/cohorts/setup.py", line 43, in <module>
        with open(path.join(current_directory, "requirements.txt"), encoding='utf-8') as f:
      File "/Users/jacquelineburos/anaconda3/envs/test-py35/lib/python3.5/codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/1x/v6qn3g750k1bh84j7m_36gpw0000gp/T/pip-build-r3nhhicf/cohorts/requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/1x/v6qn3g750k1bh84j7m_36gpw0000gp/T/pip-build-r3nhhicf/cohorts/
```

**Comment by arahuja** [comment]
The following worked for me 

```
conda create -ncohorts030 python=3.5 numpy scipy pandas
source activate cohorts030

pip install cohorts==0.3.0
```

Let me know if that gives you an errors @jburos

**Comment by jburos** [comment]
WFM on py27 & 35 - thank you @arahuja
