### ISSUE TITLE
Solve intermittent test failures

### ISSUE THREAD

**Issue by tavinathanson** [hammerlab/cohorts#201]
Mystery Python 3 failures on Travis that often clear up on re-running:

https://travis-ci.org/hammerlab/cohorts/builds

```
======================================================================
FAIL: Test that snv_count filter_fn (which using closure) falls back to the Cohort default but can be overridden.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/hammerlab/cohorts/test/test_cohort_defaults.py", line 76, in test_default_filter_fn_with_snv_count
    test_default_filter_fn(snv_count)
  File "/home/travis/build/hammerlab/cohorts/test/test_cohort_defaults.py", line 53, in test_default_filter_fn
    eq_(list(df[col]), [2, 2, 5])
nose.proxy.AssertionError: [3, 3, 6] != [2, 2, 5]
-------------------- >> begin captured stdout << ---------------------
None
{'dataframe_hash': -3694229331030615381, 'provenance_file_summary': None}
--------------------- >> end captured stdout << ----------------------
======================================================================
FAIL: Across multiple functions, test that filter_fn falls back to the Cohort default.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/hammerlab/cohorts/test/test_cohort_defaults.py", line 163, in test_default_filter_fn_multiple_functions
    ok_((df_default_arg[count_col] != df_no_arg[count_col]).any())
nose.proxy.AssertionError: None
-------------------- >> begin captured stdout << ---------------------
None
{'dataframe_hash': -3694229331030615381, 'provenance_file_summary': None}
--------------------- >> end captured stdout << ----------------------
```

**Comment by tavinathanson** [comment]
Fixed with @jburos's help in https://github.com/hammerlab/cohorts/pull/205!
